---
title: "Professional Bio"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


MARIANO VIZ is a veterinary surgeon by training, graduated with distinction in 2014 from the National University of La Plata (UNLP) in Buenos Aires, Argentina. Following graduation, he worked as an Ad Honorem Professor (2016), and then as a Research Assistant (2016-2018) in the UNLP’s Department of Rural Development while also continuing his work as a veterinarian in rural Argentina. Mariano went on to complete a specialist degree program in Human Development, focusing on sustainable development, quantitative information systems, and public policy analysis, before working abroad as a veterinarian in rural Australia. His firsthand experience as a rural vet, including witnessing the impacts of major floods on Argentinian agricultural communities and wildfires on Australia’s human and wildlife populations, increasingly led him to recognize his desire to pursue an impactful career in environmental science. Given his veterinary background, Mariano is particularly interested in issues related to the future of global food production systems and the environmental challenges posed by the increase in the global demand for animal protein. He is compelled by the Bren School's Dean, Dr. Steve Gaines, and Dr. Christopher Costello's research on the potential role of the ocean as a food supplier. Pursuing a dual specialization in Coastal Marine Resources Management and Economics and Politics of the Environment, Mariano hopes to contribute to the sustainable management of our oceans.